laberintohebras: LaberintoHebras.java Hebras.java
	javac -Xlint:all LaberintoHebras.java Hebras.java -d .

laberintoforks: LaberintoForks.java Forks.java
	javac -Xlint:all LaberintoForks.java Forks.java -d .

runhebras:
	/usr/bin/time -v java LaberintoHebras

runforks:
	/usr/bin/time -v java LaberintoForks

remove:
	rm -rf *.class
